global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Yapplr API metrics
  - job_name: 'yapplr-api'
    static_configs:
      - targets: ['yapplr-api:8080']
    metrics_path: '/metrics'
    scrape_interval: 60s
    scrape_timeout: 15s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # System metrics (if node_exporter is added later)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
