apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: analytics
    user: yapplr
    jsonData:
      version: Flux
      organization: yapplr
      defaultBucket: analytics
      tlsSkipVerify: true
    secureJsonData:
      token: yapplr-analytics-token-staging
    editable: true
