

services:
  yapplr-api:
    build:
      context: .
      dockerfile: Yapplr.Api/Dockerfile
    image: yapplr-api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${PROD_DATABASE_CONNECTION_STRING}
      - JwtSettings__SecretKey=${PROD_JWT_SECRET_KEY}
      - JwtSettings__Issuer=Yapplr.Api
      - JwtSettings__Audience=Yapplr.Client
      - JwtSettings__ExpirationInMinutes=60
      # SendGrid configuration
      - SendGridSettings__ApiKey=${PROD_SENDGRID_API_KEY}
      - SendGridSettings__FromEmail=${PROD_SENDGRID_FROM_EMAIL}
      - SendGridSettings__FromName=${PROD_SENDGRID_FROM_NAME}
      # Email provider selection
      - EmailProvider=${PROD_EMAIL_PROVIDER}
      # Firebase configuration (REQUIRED for notifications)
      - Firebase__ProjectId=${PROD_FIREBASE_PROJECT_ID}
      - Firebase__ServiceAccountKey=${PROD_FIREBASE_SERVICE_ACCOUNT_KEY}
      # Content Moderation configuration
      - ContentModeration__ServiceUrl=http://content-moderation:8000
      - ContentModeration__Enabled=true
      - ContentModeration__AutoApplyTags=false
      # RabbitMQ configuration
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__Username=${PROD_RABBITMQ_USERNAME}
      - RabbitMQ__Password=${PROD_RABBITMQ_PASSWORD}
      - RabbitMQ__VirtualHost=/
      # SignalR configuration
      - NotificationProviders__SignalR__Enabled=true
      - NotificationProviders__SignalR__MaxConnectionsPerUser=10
      - NotificationProviders__SignalR__MaxTotalConnections=10000
      - NotificationProviders__SignalR__EnableDetailedErrors=false
      # Upload configuration - override to use Docker volume path
      - Uploads__BasePath=/app/uploads
      # Redis configuration
      - Redis__ConnectionString=${PROD_REDIS_CONNECTION_STRING}
    volumes:
      - yapplr_uploads:/app/uploads
      - yapplr_logs:/app/logs
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped
    networks:
      - yapplr-network
    depends_on:
      content-moderation:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  yapplr-video-processor:
    build:
      context: .
      dockerfile: Yapplr.VideoProcessor/Dockerfile
    image: yapplr-video-processor:latest
    environment:
      - DOTNET_ENVIRONMENT=Production
      # RabbitMQ configuration
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__Username=${PROD_RABBITMQ_USERNAME}
      - RabbitMQ__Password=${PROD_RABBITMQ_PASSWORD}
      - RabbitMQ__VirtualHost=/
      # Video processing configuration
      - VideoProcessing__InputPath=/app/uploads/videos
      - VideoProcessing__OutputPath=/app/uploads/processed
      - VideoProcessing__ThumbnailPath=/app/uploads/thumbnails
      - VideoProcessing__TempPath=/app/uploads/temp
      - VideoProcessing__DeleteOriginalAfterProcessing=true
      - VideoProcessing__MaxFileSizeBytes=104857600
      - VideoProcessing__MaxDurationSeconds=300
      - VideoProcessing__VideoCodec=libx264
      - VideoProcessing__AudioCodec=aac
      # FFmpeg configuration
      - FFmpeg__BinaryPath=/usr/bin/ffmpeg
      - FFmpeg__WorkingDirectory=/tmp
      - FFmpeg__TimeoutSeconds=300
      - FFmpeg__EnableHardwareAcceleration=false
      - FFmpeg__LogLevel=error
    volumes:
      - yapplr_uploads:/app/uploads
      - yapplr_logs:/app/logs
    restart: unless-stopped
    networks:
      - yapplr-network
    depends_on:
      rabbitmq:
        condition: service_healthy

  yapplr-frontend:
    build:
      context: yapplr-frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=https://${PROD_API_DOMAIN_NAME}
        # Notification provider configuration (SignalR-only for production web)
        - NEXT_PUBLIC_ENABLE_SIGNALR=true
        # Force rebuild by passing current timestamp
        - CACHE_BUST=${CACHE_BUST:-$(date +%s)}
    image: yapplr-frontend:latest
    restart: unless-stopped
    networks:
      - yapplr-network

  content-moderation:
    build:
      context: sentiment-analysis
      dockerfile: Dockerfile
    image: content-moderation:latest
    environment:
      - PORT=8000
    restart: unless-stopped
    networks:
      - yapplr-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot
    # No dependencies - nginx can start independently and handle service availability gracefully
    restart: unless-stopped
    networks:
      - yapplr-network

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=${PROD_RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${PROD_RABBITMQ_PASSWORD}
      - RABBITMQ_DEFAULT_VHOST=/
    # No external ports exposed - only accessible from Docker network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    networks:
      - yapplr-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7.2-alpine
    command: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru --save 300 100 --save 60 1000
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - yapplr-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 768M
        reservations:
          memory: 512M

  # Logging Stack
  loki:
    image: grafana/loki:3.0.0
    # No external ports exposed - accessed through nginx proxy for security
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki
      - ./loki-config.yml:/etc/loki/local-config.yaml:ro
    restart: unless-stopped
    networks:
      - yapplr-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  grafana:
    image: grafana/grafana:10.4.0
    # No external ports exposed - accessed through nginx proxy for security
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin123}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
    restart: unless-stopped
    networks:
      - yapplr-network
    depends_on:
      - loki
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  promtail:
    image: grafana/promtail:3.0.0
    volumes:
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped
    networks:
      - yapplr-network
    depends_on:
      - loki

volumes:
  yapplr_uploads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/yapplr-prod-storage/uploads
  yapplr_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/yapplr-prod-storage/logs
  rabbitmq_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/yapplr-prod-storage/rabbitmq
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/yapplr-prod-storage/redis
  loki_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/yapplr-prod-storage/loki
  grafana_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/yapplr-prod-storage/grafana

networks:
  yapplr-network:
    driver: bridge
