server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Docker container logs
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
      # Parse Docker JSON logs
      - json:
          expressions:
            output: log
            stream: stream
            attrs:

      # Add container labels (simplified)
      - docker: {}

      # Parse structured logs from .NET applications
      - match:
          selector: '{job="docker"} |= "SourceContext"'
          stages:
            # Extract log level from the beginning
            - regex:
                expression: '^\[[\d:]+\s+(\w+)\]'
                source: output

            # Extract JSON from the end of the log line
            - regex:
                expression: '(\{.*\})$'
                source: output

            # Parse the JSON data
            - json:
                expressions:
                  source_context: SourceContext
                  request_id: RequestId
                  connection_id: ConnectionId
                  user_agent: UserAgent
                  ip_address: IpAddress
                  query_string: QueryString
                  correlation_id: CorrelationId
                  machine_name: MachineName
                  thread_id: ThreadId
                  application: Application
                  environment_name: EnvironmentName
                  process_id: ProcessId
                  environment: Environment

            # Set labels for important fields
            - labels:
                correlation_id:
                request_id:
                application:
                source_context:


