version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    command: serve

  sentiment-service:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    ports:
      - "8001:8001"
    depends_on:
      - ollama
    environment:
      - OLLAMA_URL=http://ollama:11434
      - PORT=8001
    restart: unless-stopped

volumes:
  ollama_data:
